name: Cotinuous integration and delivery
on: [push]
env:
  IMAGE: docker.pkg.github.com/fast-api-summary/web

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the master
        uses: actions/checkout@v1
      - name: Login into github packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Image
        run: |
          docker pull {{ env.IMAGE }}:latest || true
      - name: Build Image
        run: |
          docker build \
             --cache-from ${{ env.IMAGE }}:latest \
             --tag smitsgit/${{ env.IMAGE }}:latest \
             --file ./Dockerfile.prod \
             "."
      - name: Push Image
        run: |
          docker push smitsgit/${{ env.IMAGE}}:latest

  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the master
        uses: actions/checkout@v1
      - name: Login into github packages
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Image
        run: |
          docker pull {{ env.IMAGE }}:latest || true
      - name: Build Image
        run: |
          docker build \
             --cache-from ${{ env.IMAGE }}:latest \
             --tag smitsgit/${{ env.IMAGE }}:latest \
             --file ./Dockerfile.prod \
             "."
      - name: Run container
        run: |
          docker run \
             -d \
             --name fastapi-tdd \
             -e PORT=8765 \
             -e ENVIRONMENT=dev \
             -e DATABASE_TEST_URL=sqlite://sqlite.db \
             -p 5003:8765 \
             smitsgit/${{ env.IMAGE }}:latest
      - name: Run Pytest
        run: docker exec fastapi-tdd python -m pytest
#      - name: Run black
#        run: docker exec fastapi-tdd python -m black . --check
